/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { DayPlan, Language } from './types';

export const QUIZ_QUESTIONS = [
  {
    id: 'q1',
    textEn: 'I often worry that my partner will lose interest in me.',
    textAr: 'غالباً ما أشعر بالقلق من أن شريكي سيفقد اهتمامه بي.',
    category: 'anxiety',
  },
  {
    id: 'q2',
    textEn: 'I feel a strong urge to check my partner\'s social media activity.',
    textAr: 'أشعر برغبة قوية في التحقق من نشاط شريكي على وسائل التواصل الاجتماعي.',
    category: 'jealousy',
  },
  {
    id: 'q3',
    textEn: 'When my partner doesn\'t reply immediately, I start thinking of the worst-case scenarios.',
    textAr: 'عندما لا يرد شريكي على الفور، أبدأ في التفكير في أسوأ السيناريوهات.',
    category: 'overthinking',
  },
  {
    id: 'q4',
    textEn: 'I feel jealous when my partner spends time with others, even friends.',
    textAr: 'أشعر بالغيرة عندما يقضي شريكي وقتاً مع الآخرين، حتى الأصدقاء.',
    category: 'jealousy',
  },
  {
    id: 'q5',
    textEn: 'I need constant reassurance that I am loved and valued.',
    textAr: 'أحتاج إلى طمأنة مستمرة بأنني محبوب وذو قيمة.',
    category: 'anxiety',
  },
  {
    id: 'q6',
    textEn: 'I replay conversations in my head, searching for hidden meanings or signs of rejection.',
    textAr: 'أعيد تشغيل المحادثات في رأسي، باحثاً عن معانٍ خفية أو علامات رفض.',
    category: 'overthinking',
  },
  {
    id: 'q7',
    textEn: 'I feel like I am more invested in the relationship than my partner is.',
    textAr: 'أشعر أنني أستثمر في العلاقة أكثر مما يفعل شريكي.',
    category: 'anxiety',
  },
  {
    id: 'q8',
    textEn: 'I often compare myself to others and fear I will be replaced.',
    textAr: 'غالباً ما أقارن نفسي بالآخرين وأخشى أن يتم استبدالي.',
    category: 'jealousy',
  },
];

export const SEVEN_DAY_PLAN_TEMPLATE: DayPlan[] = [
  {
    dayNumber: 1,
    objectiveEn: 'Awareness and Identification',
    objectiveAr: 'الوعي وتحديد المحفزات',
    explanationEn: 'The first step is to recognize the patterns of anxious attachment and jealousy as they happen.',
    explanationAr: 'الخطوة الأولى هي التعرف على أنماط الارتباط القلق والغيرة عند حدوثها.',
    tasks: [
      {
        id: 'd1t1',
        titleEn: 'Trigger Journaling',
        titleAr: 'تدوين المحفزات',
        descriptionEn: 'Write down three moments today where you felt a spike in anxiety or jealousy.',
        descriptionAr: 'اكتب ثلاث لحظات اليوم شعرت فيها بارتفاع في القلق أو الغيرة.',
        completed: false,
        type: 'exercise',
      },
      {
        id: 'd1t2',
        titleEn: 'The 5-Minute Delay',
        titleAr: 'تأخير الـ 5 دقائق',
        descriptionEn: 'If you feel the urge to check their activity, wait 5 minutes before doing so.',
        descriptionAr: 'إذا شعرت برغبة في التحقق من نشاطهم، انتظر 5 دقائق قبل القيام بذلك.',
        completed: false,
        type: 'action',
      },
    ],
    reflectionEn: 'How did it feel to delay the urge to check?',
    reflectionAr: 'كيف كان شعورك عند تأخير الرغبة في التحقق؟',
    completed: false,
  },
  {
    dayNumber: 2,
    objectiveEn: 'Cognitive Reframing',
    objectiveAr: 'إعادة الصياغة المعرفية',
    explanationEn: 'Learning to challenge the "worst-case scenario" thoughts with more balanced perspectives.',
    explanationAr: 'تعلم تحدي أفكار "السيناريو الأسوأ" بوجهات نظر أكثر توازناً.',
    tasks: [
      {
        id: 'd2t1',
        titleEn: 'Fact vs. Fiction',
        titleAr: 'الحقيقة مقابل الخيال',
        descriptionEn: 'For every jealous thought, write one objective fact that contradicts it.',
        descriptionAr: 'لكل فكرة غيرة، اكتب حقيقة موضوعية واحدة تناقضها.',
        completed: false,
        type: 'reflection',
      },
    ],
    reflectionEn: 'What was the most challenging thought you reframed today?',
    reflectionAr: 'ما هي أصعب فكرة قمت بإعادة صياغتها اليوم؟',
    completed: false,
  },
  {
    dayNumber: 3,
    objectiveEn: 'Self-Soothing and Grounding',
    objectiveAr: 'التهدئة الذاتية والتأريض',
    explanationEn: 'Building internal stability so you don\'t rely solely on external reassurance.',
    explanationAr: 'بناء الاستقرار الداخلي حتى لا تعتمد فقط على الطمأنة الخارجية.',
    tasks: [
      {
        id: 'd3t1',
        titleEn: 'Grounding Exercise',
        titleAr: 'تمرين التأريض',
        descriptionEn: 'Practice the 5-4-3-2-1 technique when feeling overwhelmed.',
        descriptionAr: 'مارس تقنية 5-4-3-2-1 عندما تشعر بالإرهاق.',
        completed: false,
        type: 'exercise',
      },
    ],
    reflectionEn: 'Did the grounding exercise help reduce your physical anxiety?',
    reflectionAr: 'هل ساعد تمرين التأريض في تقليل قلقك الجسدي؟',
    completed: false,
  },
  {
    dayNumber: 4,
    objectiveEn: 'Boundary Setting (Internal)',
    objectiveAr: 'وضع الحدود (الداخلية)',
    explanationEn: 'Setting limits on how much time you spend overthinking or checking social media.',
    explanationAr: 'وضع حدود للوقت الذي تقضيه في التفكير الزائد أو التحقق من وسائل التواصل الاجتماعي.',
    tasks: [
      {
        id: 'd4t1',
        titleEn: 'Social Media Fast',
        titleAr: 'صيام وسائل التواصل',
        descriptionEn: 'Avoid checking your partner\'s social media for 4 consecutive hours.',
        descriptionAr: 'تجنب التحقق من وسائل التواصل الاجتماعي لشريكك لمدة 4 ساعات متتالية.',
        completed: false,
        type: 'action',
      },
    ],
    reflectionEn: 'What did you do with the extra time and mental energy?',
    reflectionAr: 'ماذا فعلت بالوقت والطاقة الذهنية الإضافية؟',
    completed: false,
  },
  {
    dayNumber: 5,
    objectiveEn: 'Value-Based Living',
    objectiveAr: 'العيش القائم على القيم',
    explanationEn: 'Focusing on your own life, hobbies, and goals independent of the relationship.',
    explanationAr: 'التركيز على حياتك الخاصة، هواياتك، وأهدافك بشكل مستقل عن العلاقة.',
    tasks: [
      {
        id: 'd5t1',
        titleEn: 'Solo Activity',
        titleAr: 'نشاط فردي',
        descriptionEn: 'Spend 1 hour doing something you love that doesn\'t involve your partner.',
        descriptionAr: 'اقضِ ساعة واحدة في فعل شيء تحبه ولا يشمل شريكك.',
        completed: false,
        type: 'action',
      },
    ],
    reflectionEn: 'How did it feel to prioritize yourself today?',
    reflectionAr: 'كيف كان شعورك عند إعطاء الأولوية لنفسك اليوم؟',
    completed: false,
  },
  {
    dayNumber: 6,
    objectiveEn: 'Effective Communication',
    objectiveAr: 'التواصل الفعال',
    explanationEn: 'Learning to express needs without blame or excessive demand for reassurance.',
    explanationAr: 'تعلم التعبير عن الاحتياجات دون لوم أو طلب مفرط للطمأنة.',
    tasks: [
      {
        id: 'd6t1',
        titleEn: '"I" Statements',
        titleAr: 'جمل الـ "أنا"',
        descriptionEn: 'Practice phrasing a need using "I feel... when... because...".',
        descriptionAr: 'تدرب على صياغة حاجة باستخدام "أشعر بـ... عندما... لأن...".',
        completed: false,
        type: 'exercise',
      },
    ],
    reflectionEn: 'Did you notice a difference in how your partner responded?',
    reflectionAr: 'هل لاحظت فرقاً في كيفية استجابة شريكك؟',
    completed: false,
  },
  {
    dayNumber: 7,
    objectiveEn: 'Integration and Maintenance',
    objectiveAr: 'التكامل والاستمرارية',
    explanationEn: 'Reviewing progress and committing to long-term emotional balance.',
    explanationAr: 'مراجعة التقدم والالتزام بالتوازن العاطفي على المدى الطويل.',
    tasks: [
      {
        id: 'd7t1',
        titleEn: 'Growth Review',
        titleAr: 'مراجعة النمو',
        descriptionEn: 'List three ways you have grown in your emotional regulation this week.',
        descriptionAr: 'اذكر ثلاث طرق نموت فيها في تنظيمك العاطفي هذا الأسبوع.',
        completed: false,
        type: 'reflection',
      },
    ],
    reflectionEn: 'What is your commitment to yourself for the next month?',
    reflectionAr: 'ما هو التزامك تجاه نفسك للشهر القادم؟',
    completed: false,
  },
];

export const TRANSLATIONS = {
  en: {
    welcome: 'Welcome to Inner Balance Pro',
    tagline: 'Your Personalized Emotional AI Coach',
    getStarted: 'Get Started',
    language: 'Language',
    next: 'Next',
    back: 'Back',
    finish: 'Finish',
    onboarding: {
      step1Title: 'Identify Your Pattern',
      step1Desc: 'Let\'s understand your emotional triggers to build a better plan.',
      step2Title: 'Language Preference',
      step2Desc: 'Choose your preferred language for the journey.',
      step3Title: 'Emotional Assessment',
      step3Desc: 'Please answer honestly. This stays private.',
      step4Title: 'Your Profile Analysis',
      step4Desc: 'Here is what we found based on your responses.',
      step5Title: 'Your 7-Day Plan',
      step5Desc: 'We have generated a custom path for your growth.',
    },
    dashboard: {
      title: 'Dashboard',
      todayPlan: 'Today\'s Plan',
      progress: 'Progress',
      streak: 'Day Streak',
      emergency: 'Emergency Mode',
      chat: 'Chat with Coach',
      status: 'Emotional Status',
    },
    emergency: {
      title: 'Emergency Calm',
      breathing: 'Breathe with the circle...',
      grounding: 'Grounding Exercise',
      reframe: 'Reframe the Thought',
      interrupt: 'Interrupt the Loop',
    },
    types: {
      'Anxious-High': 'High Anxious Attachment',
      'Anxious-Moderate': 'Moderate Anxious Attachment',
      'Secure': 'Secure Attachment',
      'Mixed': 'Mixed Attachment Pattern',
    },
  },
  ar: {
    welcome: 'مرحباً بك في Inner Balance Pro',
    tagline: 'مدربك العاطفي الشخصي بالذكاء الاصطناعي',
    getStarted: 'ابدأ الآن',
    language: 'اللغة',
    next: 'التالي',
    back: 'السابق',
    finish: 'إنهاء',
    onboarding: {
      step1Title: 'حدد نمطك',
      step1Desc: 'دعنا نفهم محفزاتك العاطفية لبناء خطة أفضل.',
      step2Title: 'تفضيل اللغة',
      step2Desc: 'اختر لغتك المفضلة للرحلة.',
      step3Title: 'التقييم العاطفي',
      step3Desc: 'يرجى الإجابة بصدق. هذا يبقى خاصاً.',
      step4Title: 'تحليل ملفك الشخصي',
      step4Desc: 'إليك ما وجدناه بناءً على إجاباتك.',
      step5Title: 'خطتك لمدة 7 أيام',
      step5Desc: 'لقد أنشأنا مساراً مخصصاً لنموك.',
    },
    dashboard: {
      title: 'لوحة التحكم',
      todayPlan: 'خطة اليوم',
      progress: 'التقدم',
      streak: 'سلسلة الأيام',
      emergency: 'وضع الطوارئ',
      chat: 'تحدث مع المدرب',
      status: 'الحالة العاطفية',
    },
    emergency: {
      title: 'هدوء الطوارئ',
      breathing: 'تنفس مع الدائرة...',
      grounding: 'تمرين التأريض',
      reframe: 'أعد صياغة الفكرة',
      interrupt: 'اقطع الحلقة',
    },
    types: {
      'Anxious-High': 'ارتباط قلق (مرتفع)',
      'Anxious-Moderate': 'ارتباط قلق (متوسط)',
      'Secure': 'ارتباط آمن',
      'Mixed': 'نمط ارتباط مختلط',
    },
  },
};
